- name: configure locales
  locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ locales }}"
  become: yes
  register: locale_configure

- name: gen locale
  command: /usr/sbin/locale-gen
  become: yes
  when: locale_configure.changed

- name: set locale
  command: "/usr/sbin/update-locale LANG={{ locale }} LC_ALL={{locale}}"
  become: yes
  when: locale_configure.changed

- name: set /etc/localtime
  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link
  become: yes

- name: set /etc/timezone
  template: src=timezone dest=/etc/timezone
  notify: update tzdata
  become: yes
