- name: Set default locale to en_US.UTF-8
  debconf:
    name: locales
    question: locales/default_environment_locale
    value: "{{ locale }}"
    vtype: select

- name: set to generate locales
  debconf:
    name: locales
    question: locales/locales_to_be_generated
    value: en_US.UTF-8 UTF-8, ru_RU.UTF-8 UTF-8
    vtype: multiselect

- name: set /etc/localtime
  file:
    src: "/usr/share/zoneinfo/{{ timezone.areas }}/{{timezone.zone}}"
    dest: /etc/localtime
    state: link
  become: yes

- name: set /etc/timezone
  template:
    src: timezone
    dest: /etc/timezone
  become: yes

- name: update timezone areas
  debconf:
    name: tzdata
    question: tzdata/Areas
    value: "{{timezone.areas}}"
    vtype: select
  become: yes

- name: update timezone zone
  debconf:
    name: tzdata
    question: "tzdata/Zones{{timezone.zone}}"
    value: "{{timezone.areas}}"
    vtype: select
  become: yes
