---

- name: fix resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
  become: yes
  failed_when: false

- import_tasks: 'repos.yml'

- import_tasks: 'update.yml'

- import_tasks: 'install.yml'

- stat: path=/etc/cloud/cloud.cfg
  register: cloud_cfg
  when: ansible_distribution == 'Ubuntu'

- lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^preserve_hostname:'
    line: 'preserve_hostname: true'
  when: cloud_cfg is defined and cloud_cfg.stat is defined and cloud_cfg.stat.exists == True
  become: yes
  notify: os reboot

- hostname:
    name: "{{ hostname | default(inventory_hostname, true) }}"
  become: yes
  notify: os reboot

- name: enable SSH forwarding for sudo
  lineinfile:
    dest: /etc/sudoers
    insertafter: '^#?\s*Defaults\s+env_keep\b'
    line: 'Defaults    env_keep += "SSH_AUTH_SOCK"'
  become: yes

- import_tasks: 'locale_timezone.yml'