---

- import_tasks: 'repos.yml'

- import_tasks: 'update.yml'

- import_tasks: 'install.yml'

- stat: path=/etc/cloud/cloud.cfg
  register: cloud_cfg

- lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^preserve_hostname:'
    line: 'preserve_hostname: true'
  when: cloud_cfg.stat.exists == True
  become: yes
  notify: os reboot

- hostname:
    name: "{{ hostname }}"
  when: hostname is defined
  become: yes
  notify: os reboot

- name: enable SSH forwarding for sudo
  lineinfile:
    dest: /etc/sudoers
    insertafter: '^#?\s*Defaults\s+env_keep\b'
    line: 'Defaults    env_keep += "SSH_AUTH_SOCK"'
  become: yes

- import_tasks: 'locale_timezone.yml'