---

- name: enable repos
  become: yes
  replace:
    path: /etc/apt/sources.list
    regexp: '^(deb.+\s*bionic\S*\s+main)\s*$'
    replace: '\1 restricted universe multiverse'
  when: ansible_distribution == 'Ubuntu'

- name: enable repos
  become: yes
  replace:
    path: /etc/apt/sources.list
    regexp: '^(deb.+\s*buster\S*\s+main)\s*$'
    replace: '\1 contrib non-free'
  when: ansible_distribution == 'Debian'
